openapi: 3.0.1
info:
  title: metatile-queue-populator
  description: Service for adding metatiles to a queue based on variety of inputs
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /tiles:
    post:
      operationId: postTilesByBbox
      summary: add the all the meta tiles in the given bbox and zoom range into the queue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tilesRequest'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        409:
          $ref: '#/components/responses/Conflict'
        5XX:
          $ref: '#/components/responses/UnexpectedError'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    tilesRequest:
      type: object
      required:
        - bbox
        - minZoom
        - maxZoom
      properties:
        bbox:
          type: array
          description: WGS84 bbox
          items:
            type: integer
          minItems: 4
          maxItems: 4
        minZoom:
          type: integer
          minimum: 0
          maximum: 18
        maxZoom:
          type: integer
          minimum: 0
          maximum: 18
