{{- $chartName := include "metatile-queue-populator.name" . -}}
{{- $tracingUrl := include "metatile-queue-populator.tracingUrl" . -}}
{{- $metricsUrl := include "metatile-queue-populator.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{- with .Values.dbConfig }}
  DB_HOST: {{ .host }}
  DB_NAME: {{ .database }}
  DB_SCHEMA: {{ .schema }}
  DB_PORT: {{ .port | quote }}
  {{- end -}}
  {{- with .Values.queueConfig }}
  QUEUE_JOBS_EXPIRE_IN_SECONDS: {{ .expireInSeconds | quote }}
  QUEUE_JOBS_RETRY_BACKOFF: {{ .retryBackoff | quote }}
  QUEUE_JOBS_RETRY_LIMIT: {{ .retryLimit | quote }}
  QUEUE_JOBS_RETRY_DELAY_SECONDS: {{ .retryDelaySeconds | quote }}
  QUEUE_JOBS_RETENTION_HOURS: {{ .retentionHours | quote }}
  {{- end -}}
  {{- if .Values.dbConfig.sslAuth.enabled }}
  DB_ENABLE_SSL_AUTH: "true"
  DB_CERT_SECRET_NAME: {{ .Values.dbConfig.sslAuth.secretName }}
  DB_CERT_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.caFileName }}
  {{- else }}
  DB_ENABLE_SSL_AUTH: "false"
  {{- end }}
  APP_PROJECT_NAME: {{ .Values.env.projectName | quote }}
  APP_ENABLE_REQUEST_QUEUE_HANDLING: {{ .Values.env.enableRequestQueueHandling | quote }}
  APP_REQUEST_QUEUE_CHECK_INTERVAL_SEC: {{ .Values.env.requestQueueCheckIntervalSec | quote }}
  APP_TILES_BATCH_SIZE: {{ .Values.env.tilesBatchSize | quote }}
  APP_METATILE_SIZE: {{ .Values.env.metatileSize | quote }}
{{- end }}
