{
 "title": "metatile-queue-populator - instance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,10m,30m,1h,6h,12h,1d" },
   { "name": "projectName", "label": "project name", "query": { "query": "label_values(project)" } },
   { "name": "source", "query": { "query": "label_values(source)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(metatile_queue_populator_populate_requests_handled{project=\"$projectName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "population requests handled and retries since restart",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metatile_queue_populator_populate_requests_handled{project=\"$projectName\", source=\"$source\", instance=\"$instance\"}",
     "legendFormat": "{{retrycount}}"
    }
   ]
  },
  {
   "title": "batches handled since restart",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metatile_queue_populator_request_batches_handled{project=\"$projectName\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "requests in queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metatile_queue_populator_tiles_requests_queue_current_count{project=\"$projectName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tiles in queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metatile_queue_populator_tiles_queue_current_count{project=\"$projectName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total populated since restart",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source) (metatile_queue_populator_metatiles_populated{project=\"$projectName\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "populated from api source since restart",
   "type": "stat",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 6 },
   "repeat": "source",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metatile_queue_populator_metatiles_populated{project=\"$projectName\", source=\"api\", instance=\"$instance\"}",
     "legendFormat": "Z{{z}}"
    }
   ]
  },
  {
   "title": "populated from expiredTiles source since restart",
   "type": "stat",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metatile_queue_populator_metatiles_populated{project=\"$projectName\", source=\"expiredTiles\", instance=\"$instance\"}",
     "legendFormat": "Z{{z}}"
    }
   ]
  },
  {
   "title": "metatiles populated in $interval window",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (source, z) (increase(metatile_queue_populator_metatiles_populated{project=\"$projectName\", source=\"$source\", instance=\"$instance\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "population duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(metatile_queue_populator_population_seconds_bucket{project=\"$projectName\", source=\"$source\", instance=\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(metatile_queue_populator_population_seconds_bucket{project=\"$projectName\", source=\"$source\", instance=\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "rate(metatile_queue_populator_population_seconds_sum{project=\"$projectName\", source=\"$source\", instance=\"$instance\"}[$interval]) / rate(metatile_queue_populator_population_seconds_count{project=\"$projectName\", source=\"$source\", instance=\"$instance\"}[$interval])",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{project=\"$projectName\", instance=\"$instance\"}[$interval]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{project=\"$projectName\", instance=\"$instance\"}[$interval]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{project=\"$projectName\", instance=\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{project=\"$projectName\", instance=\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{project=\"$projectName\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}